//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlab2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tlab2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на aberration/аберрация, отклонение
        ///abnormal operation/ненормальная работа
        ///abrasion/истирание, трение
        ///abrasive/абразивный; шлифовальный материал (паста, наждачная бумага)
        ///absorbent/поглотитель, абсорбент; сглаживающий (о фильтре)
        ///absorber/поглотитель
        ///absorption/поглощение, абсорбция
        ///abut/прилегать, примыкать
        ///AC input power/входное питание переменного тока
        ///AC power/питание переменного тока
        ///AC voltage/переменное напряжение
        ///acceptable/приемлемый, допустимый
        ///access/доступ (к узлу, детали; к памяти)
        ///ac [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string listbox1 {
            get {
                return ResourceManager.GetString("listbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на aberration/аберрация, отклонение
        ///abnormal operation/ненормальная работа
        ///abrasion/истирание, трение
        ///abrasive/абразивный; шлифовальный материал (паста, наждачная бумага)
        ///absorbent/поглотитель, абсорбент; сглаживающий (о фильтре)
        ///absorber/поглотитель
        ///absorption/поглощение, абсорбция
        ///abut/прилегать, примыкать
        ///AC input power/входное питание переменного тока
        ///AC power/питание переменного тока
        ///AC voltage/переменное напряжение
        ///acceptable/приемлемый, допустимый
        ///access/доступ (к узлу, детали; к памяти)
        ///ac [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string listbox2 {
            get {
                return ResourceManager.GetString("listbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на aberration/аберрация, отклонение
        ///abnormal operation/ненормальная работа
        ///abrasion/истирание, трение
        ///abrasive/абразивный; шлифовальный материал (паста, наждачная бумага)
        ///absorbent/поглотитель, абсорбент; сглаживающий (о фильтре)
        ///absorber/поглотитель
        ///absorption/поглощение, абсорбция
        ///abut/прилегать, примыкать
        ///AC input power/входное питание переменного тока
        ///AC power/питание переменного тока
        ///AC voltage/переменное напряжение
        ///acceptable/приемлемый, допустимый
        ///access/доступ (к узлу, детали; к памяти)
        ///ac [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [ A ]
        ///aberration/���������, ����������
        ///abnormal operation/������������ ������
        ///abrasion/���������, ������
        ///abrasive/����������; ������������ �������� (�����, ��������� ������)
        ///absorbent/�����������, ���������; ������������ (� �������)
        ///absorber/�����������
        ///absorption/����������, ���������
        ///abut/���������, ���������
        ///AC input power/������� ������� ����������� ����
        ///AC power/������� ����������� ����
        ///AC voltage/���������� ����������
        ///acceptable/����������, ����������
        ///access/������ (� ����, ������; � ���� [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
    }
}
